### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by kareemsulthan07** [RainwayApp/warden#5]
Hi.,
While executing the WardenExample project in VS 2017 15.3 i'm getting "Access denied" error. And, here is exception details, 
Warden.Core.Exceptions.WardenException occurred
  HResult=0x80131500
  Message=Access denied 
  Source=Warden
  StackTrace:
   at Warden.Core.WardenManager.Initialize(Boolean killTressOnExit) in E:\Projects\Gits\warden\Warden\Core\WardenManager.cs:line 45
   at WardenExample.Program.<Start>d__1.MoveNext() in E:\Projects\Gits\warden\WardenExample\Program.cs:line 30
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WardenExample.Program.Main(String[] args) in E:\Projects\Gits\warden\WardenExample\Program.cs:line 25

Inner Exception 1:
ManagementException: Access denied

**Comment by Codeusa** [comment]
Warden requires administrator privileges for your application. There is currently no polling fallback.
